# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_list', '0001_squashed_0004_account_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
