# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 23:05
from __future__ import unicode_literals

from django.db import migrations
from django.core.management import call_command

fixture = 'initial_data'

def load_fixture(apps, schema_editor):
    call_command('loaddata', fixture, app_label='task_list')

def unload_fixture(apps, schema_editor):
    "Brutally deleting all entries for this model..."
    account = apps.get_model("task_list", "Account")
    account.objects.all().delete()

    task = apps.get_model("task_list", "Task")
    task.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ("task_list", "0001_initial")
    ]

    operations = [
        migrations.RunPython(load_fixture, reverse_code=unload_fixture),
    ]
