# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 12:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_list', '0002_load_initial_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by', to='task_list.Account'),
        ),
    ]
