# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_list', '0002_remove_task_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
