# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 16:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_list', '0002_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='is_admin',
        ),
    ]
