# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 15:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_list', '0004_auto_20160717_1513'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='is_completed',
            new_name='status',
        ),
    ]
