# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 16:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_account'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
